# Generated by Django 3.2 on 2023-07-06 07:25

import api.validators
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230705_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь стаким именем уже существует'}, help_text='Не больше 150 символов.Только буквы, цифры и @/./+/-/_', max_length=150, unique=True, validators=[api.validators.validate_username, django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Пользователь'),
        ),
    ]
